### ISSUE TITLE
관심상품목록 화면 오버플로우

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-mobile-app#19]
좋아요 화면에서 물품명이 20자인 물품에서 다음과 같이 오버플로우가 나는 것 같습니당! (아이폰8기준)
시간되실때 Shortener.shortenStrTo()로 한번 감싸주셔도 될 것 같아유 ㅎㅎ

<img width="263" alt="스크린샷 2022-09-19 오후 11 23 23" src="https://user-images.githubusercontent.com/51855129/191040592-b1d88c4d-09af-4721-8bfb-2e7048bdc966.png">

**Comment by minji1110** [comment]
다음과 같이 수정 완료
![Simulator Screen Shot - iPhone 8 - 2022-09-21 at 14 03 18](https://user-images.githubusercontent.com/70498432/191419018-e1a19683-fa08-41ec-b063-0540c02561dc.png)

추가로, str의 길이로는 최대 어느정도인지 가늠이 어려운 경우가 있을 것 같아서
다음과 같이 보여질 최대 줄수를 넘겨줄 수 있도록 하는 함수도 추가했습니다!

``` dart
  static shortenStrWithMaxLines(String? text, int maxLine) {
    return Text(
      text!,
      maxLines: maxLine,
      overflow: TextOverflow.ellipsis,
    );
  }
```
(이렇게 할 경우 custom text들과 함께 사용하기가 애매해져서 해당 부분 다른 이슈로 올려놓았습니다!)
