### ISSUE TITLE
메인 페이지 - 교환요청목록 overflow

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#21]
<img src="https://user-images.githubusercontent.com/70498432/191643979-dd7fea56-62aa-4f40-a6b2-56eb739ff75f.png" width="50%">
아이폰 8 시뮬레이터로 돌려보았을 때 오버플로우가 발생하네요..! 확인 부탁드립니다~!

**Comment by hanslelee** [comment]
아이고 알려주셔서 감사드립니다~~! 해당 오류를 수정하던 중에 사소하게 궁금한 점이 생겨 질문 드립니당 
현재 코드가 이런 식으로 되어있는데 
<img width="704" alt="스크린샷 2022-10-05 오후 4 04 49" src="https://user-images.githubusercontent.com/51855129/194000834-2344bc6a-3240-45c6-b878-8bdaf90f176e.png">

예를 들어, 물품명이 짧은데 닉네임의 길이가 5 인경우에 다음과 같이 나오게 되는데 좀 이상해보이는 것 같아서요...ㅠㅜ 반대의 경우도 마찬가지구요...
<img width="245" alt="image" src="https://user-images.githubusercontent.com/51855129/194001439-37a6a256-8c30-4e86-8cac-b74806398f3f.png">

어떻게 하는 게 좋을지 민지님의 의견은 어떤지 여쭙고 싶습니다!

**Comment by minji1110** [comment]
@hanslelee 저도 상품 검색 화면 작성하면서 '상품명 | 닉네임 ' 형태로 보여져야하는데 되게 애매하네요ㅜㅜ 해두신거처럼 우선 두가지 각각 제한글자를 두는걸로 할까요..?

**Comment by hanslelee** [comment]
@minji1110 넵 그럼 일단 두겠습니당! 더 좋은 아이디어 생각나면 바꾸면 좋을 것 같아요😊👍
