### ISSUE TITLE
custom text 관련 오류

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#25]
![Simulator Screen Shot - iPhone 8 - 2022-10-08 at 18 55 32](https://user-images.githubusercontent.com/70498432/194701743-d634e621-3888-4f7a-a9f6-3ce5d145a39f.png)
<img width="687" alt="스크린샷 2022-10-08 오후 6 55 42" src="https://user-images.githubusercontent.com/70498432/194701747-02a1ec54-be1e-4c0a-aa96-7fdc93d99e16.png">

@hanslelee 새로 작성해주신 R12Text 가 사용되는곳들에서 저는 저렇게 오류가 뜨는데 혹시 제가 뭔가 설정을 잘못한걸까요..?? 발견을 못하셨을리가 없는데 저만 그런가 싶어서요ㅠㅠ 우선 이슈에 올려두겠습니다!

**Comment by hanslelee** [comment]
@minji1110 허걱스 ㅠㅠㅠ 제가 그 PR을 코드 예시로 편하게 확인하시면 좋을 것 같아서 올려놓은 거라 R12Text사용되는 부분들을 모두 변경된 사항에 맞게 수정하지 않아서 저런 것 같아요 까먹고 있었네요...ㅠㅠㅠ 피드백 주시면 다른 Text위젯들도 다 한꺼번에 수정해서 PR 머지하려고 생각했었는데 그 부분을 제가 제대로 전달을 잘 못한것 같네요 흑흑 죄송합니다 오늘중으로 다른 Text위젯들도 Params 적용하고 나머지도 그에 맞게 일괄 수정해서 PR 다시 올리겠습니다!!!
