### ISSUE TITLE
첫 위젯의 multiprovider 에 모든 provider를 넣는 방법에 대하여

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#28]
개발을 하다보니까 부모 위젯에 원하는 provider 가 없어서 새로 provider를 다시 지정해야하는 경우가 꽤 있는 것 같습니다..
특히 bottom modal을 작성하면 child로 생성되는게 아니라서 provider를 새로 넘겨주어야하는데, 이렇게 되면 이전의 provider가 가지던 값과 달라져서 원하는대로 작동이 안되어서요ㅠㅠ 
혹시 애초에 NavadaApp 위젯(첫 위젯) 에 모든 provider를 두는 것은 좋은 방법이 아닐까요..? 어떻게 생각하시는지 궁금합니다!

**Comment by hanslelee** [comment]
@minji1110 저도 앱 전체에서 공통적으로 사용되는 provider들은 NavadaApp 위젯에서 처음에 생성하는 것이 좋을 것 같습니다!👍👍 
예외적으로 해당 스크린에서 새로 생성해야하는 provider같은 경우엔 원래 방식으로 사용하는 걸로 할까요?!

예를 들어, 새 상품을 등록할 때 사용하는 CreateProductProvider같은 경우, 전체 앱에서 하나만 두고 사용하는 것이 아니라 새로 상품을 등록할때마다 새로운 프로바이더가 필요하기 때문에 이런 경우엔 상품등록 화면에서 CreateProductProvider 생성하는 것으로 하면 될 것 같습니다.
혹시 이와 같은 예시와 비슷한 상황인데 모달을 사용하셔야 할 경우에는 다음과 같이 원하는 프로바이더를 뿌리로 모달을 생성하셔도 될 것 같습니다. 알고 계셨다면 도움이 되지 않겠지만 혹시 참고하시면 편하실까 해서 코드 남겨놓겠습니다 ㅎㅎ([참고 글](https://velog.io/@hssarah/showModalBottomSheet%EC%97%90%EC%84%9C-Consumer-%EC%82%AC%EC%9A%A9%EC%8B%9C-Parent-%EC%9C%84%EC%A0%AF%EC%9D%98-Provider-%EB%B0%9C%EA%B2%AC-%EB%AA%BB%ED%95%98%EB%8A%94-%EC%98%A4%EB%A5%98))
```dart
_showCustomModal(BuildContext? context) {
    final provider = Provider.of<CreateProductProvider>(context!, listen: false);
    
    showModalBottomSheet(
      context: context,
      builder: (context) {
        return ChangeNotifierProvider.value(value: provider, child: CustomModal());
      },
    );
  }
```

**Comment by minji1110** [comment]
@hanslelee 감사합니다!! 그럼 공통으로 필요한것들은 그렇게 다시 수정해보겠습니다 .. ㅠㅠ 
말씀하신 경우는 프로바이더가 새로 필요한 경우 맞나요?

제가 지금 잘 안되는 부분이 [ 카테고리 선택 버튼 클릭 -> 카테고리 모달 창 띄움 ]  부분인데,
카테고리 선택 위젯을 A, 카테고리 모달창을 B 라고 할 때
A -> B 로 선택되었던 카테고리들을 알려줘서 그 카테고리들은 선택된채로 보여져야되고,
B -> A 로 새로 선택된 애들을 알려줘서 다시 api 요청을 해야합니다.

즉 A <-> B 사이에 카테고리 리스트가 유지되어야해서 provider를 새로 받아오면 안되고 그대로 유지해야하는데, 이 경우 말씀하신 코드를 쓸 수 있는건가요..? 

지금은 A에서 쓰던 프로바이더를 B 한테 인자로 넘겨주는방식으로 두었는데, 그렇게되면 위에서 말한것들은 제대로 동작하지만
버튼 누르는 즉시마다 UI에 반영이 안되더라구요ㅠㅠ 이유는 모르겠어서 우선 두었습니다

제가 너무 말을 어렵게 한거같은데.. 혹시 알고계신 이유가 있나 궁금합니다..!
우선은 최상위 위젯에 프로바이더를 두고, 카테고리 위젯 벗어나는경우에는 전부 reset 하는 식으로 다시 짜보겠습니다 흑흑

**Comment by hanslelee** [comment]
@minji1110 옴... 제가 제대로 이해한 게 맞는지 잘 모르겠어서 확실하게 말씀드리기가 어렵긴 한데 
플러터에서 모달을 생성하는 경우 원래 있던 위젯트리위에 모달이 생성되는 게 아니라 다른 위젯트리에 모달이 생성된다 하네요 
그래서 모달에서는 다른 위젯트리에 부모위젯이 있으니 부모위젯의 프로바이더도 Consume할 수 없었던 것 같아요 ㅠㅠ

위에 제가 작성한 코드를 사용했을 때는 모달을 생성할때 부모위젯에서 만들어놓은 프로바이더를 뿌리로 하여 모달을 자식으로 생성하기 때문에 같은 프로바이더를 위젯트리내에서 사용하게 됩니다! 전에 교환완료 화면에서 별점주는 모달을 개발할때 위 코드를 사용했는데 예상했던 것과 동일한 방식으로 작동했습니다. 다시말하자면 부모위젯의 프로바이더를 모달에서도 이상없이 사용할 수 있었습니다. 부모위젯과 자식모달위젯이 동일한 위젯트리안에 있었기 때문인것같습니다.

아마 말씀하신 현상의 이유로는, 인자로 넘겨주는 경우엔 A위젯과 B모달창이 다른 위젯트리상에 있어서 프로바이더의 notifilisteners가 제대로 작동이 되지 않은것은 아닐까 확실하진 않지만 추측해봅니다... 부모 위젯과 자식 모달위젯간의 같은 프로바이더를 이상없이 사용하기 위해선 두가지가 같은 위젯트리 내에 있어야 하는 것이 좀 더 확실한 방식인 것 같다는 생각이 드네요...?! 

예시로 들었던 상품등록프로바이더나 혹은 교환별점주기프로바이더 같은 경우엔 화면을 생성할때마다 리셋이 되어야 한다고 생각해서 화면마다 새로운 프로바이더가 필요하다고 느껴졌습니다 ㅠ.ㅜ

**Comment by minji1110** [comment]
@hanslelee 헉 맞아요 제가 말한게 같은 위젯트리상에 있기를 원한다는거였습니당.. 
아니 진작 여쭤볼걸 그랬네요 ㅠㅠㅠ 바로 동작합니다.. 감사합니다 !!!!

**Comment by minji1110** [comment]
혹시 모달 내에서 프로바이더 2개가 필요한경우에는 어떻게 해야하는지 아시나요??
지금 코드로는 굳이 필요 없긴 한데 그렇게 되면 코드가 좀더 깔끔해질 것 같아서요..!!

**Comment by hanslelee** [comment]
잘 동작한다니 다행이네요 😊😊 말씀하신 경우에 관해서는 서치해봤는데 레퍼런스를 찾기가 힘드네요 😭😭 
찾으면 바로 알려드리도록 하겠습니다!! 민지님도 만약 알게되신다면 제게도 알려주시면 감사하겠습니다 ㅎㅎㅎ
