### ISSUE TITLE
홈화면 오버플로우 Wrap 방식에 관하여 도움을 부탁드립니다~!~!

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-mobile-app#31]
회원의 닉네임을 10자로 늘려보았는데 다음과 같이 오버플로우가 나는 것을 확인했습니다.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/51855129/195513049-e791c99f-addb-4486-8dcb-676a2f4e1d1c.png">

해결하려고 Wrap으로 감싸보았는데 이렇게 되네요..
<img width="272" alt="image" src="https://user-images.githubusercontent.com/51855129/195513164-6d6f4531-eee6-4366-82d3-f1688901562a.png">

다음과 같은 결과가 나오면 좋겠는데 여러가지 방법을 시도해보아도 마음처럼 잘 되지 않습니다 ㅜ.ㅜ 다음과 같이 만들면 닉네임이 짧을 경우엔 이상하게 보이고...😭
<img width="268" alt="image" src="https://user-images.githubusercontent.com/51855129/195513554-9b44e75f-3be4-47dd-9aa5-a37f75242e4e.png">

혹시 어떤것이든 아이디어 있으시면 알려주시면 감사하겠습니다!! @minji1110

**Comment by minji1110** [comment]
<img width="276" alt="스크린샷 2022-10-13 오후 7 22 56" src="https://user-images.githubusercontent.com/70498432/195572122-638eb2c9-53d4-424f-9c19-31ac79f572f1.png">
저는 이렇게 짧은 경우에도 이상하지 않은 것 같은데, 닉네임 길이 상관없이 그냥 항상 두줄로 보여지는것은 어떨까요?? 한슬님이 보기에는 많이 이상한가요..?😅😅

![flutter_01](https://user-images.githubusercontent.com/70498432/195572613-c1ead937-6b77-40d1-862e-ed36651fb025.png)

추가로, 제 경우에는 아직 오버플로우가 보여서요! 혹시 아직 수정 안된부분인가용??

**Comment by hanslelee** [comment]
@minji1110 저도 제안해주신 디자인도 좋은 것 같아요😊😊 그럼 저렇게 수정하도록 하겠습니다!!

아이고 죄송합니다 ㅠㅠ 오버플로우 수정했었는데
커스텀 텍스트 수정하면서 홈에 저부분도 건드리면서 오버플로우가 또 난 것 같네요😭😭
앞으론 더 꼼꼼히 확인하겠습니다 이번 스프린트에 수정해서 같이 PR 올리겠습니다!
