### ISSUE TITLE
앱 디자인 : 교환 내역 화면 컨펌

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#37]
<img width="545" alt="스크린샷 2022-10-25 오후 11 15 51" src="https://user-images.githubusercontent.com/70498432/197798166-3ee48c8d-6706-4bfb-90f9-4b14c2fa7468.png">

다음과 같이 교환내역 화면을 구성해보았는데, 보여드린 후에 모바일 개발 진행해야할 것 같아서 이슈에 올립니다!
상대별점 / 내 별점 보이게 했고, 왼쪽의 기간설정의 경우 백앤드상으로는 없긴 한데.. 혹시 넣는게 나을까 싶어 드롭다운만 만들어봤습니당
수정 필요한 부분 말씀 부탁드려요!

------------------------------------------------------------------------------------------------------------------------

+) 생각해보니 교환내역에 교환중 + 교환완료를 넣기로 한 것 같은데, 교환 내역이라는건 말그대로 어떤 교환들을 했는지 보여주는거니까
교환완료만 보여지는게 맞지 않을까 해서요.. 거래 현황과의 차이점이 필요할 것 같아서
그렇게 되면 교환을 완료할 수 있는 화면 즉, 교환중인 거래의 상세 페이지가 두개가 되는것 같아서 이부분도 어떻게 하는게 좋을지 여쭤보고싶습니다!

[화면1]
<img width="411" alt="스크린샷 2022-10-25 오후 11 34 44" src="https://user-images.githubusercontent.com/70498432/197803006-5e6ba171-973d-4649-af88-f934cfff8c34.png">

[화면2]
<img width="1015" alt="스크린샷 2022-10-25 오후 11 35 03" src="https://user-images.githubusercontent.com/70498432/197803034-5f1710f9-11f0-4b05-9372-ddbd97efe76d.png">

**Comment by minji1110** [comment]
@hanslelee 네네 그거 말한거 맞아요! 아 교환완료하기 제목이 아예 교환중으로 통일된거였군요 이해했습니당
그럼 말씀하신대로 교환중 / 교환완료 분리하는걸로 할까요..??

**Comment by hanslelee** [comment]
@minji1110 넵 좋아요~! 그럼 일단 피그마 그렇게 수정해놓겠습니다!
