### ISSUE TITLE
교환중 상세보기 화면 에러

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#39]
<img src="https://user-images.githubusercontent.com/70498432/206841861-59e49561-6ef1-4919-947e-54eef648ac91.PNG" width="40%">    <img src="https://user-images.githubusercontent.com/70498432/206841864-7244f0f5-3e3a-4641-bcc3-c29664f35a8d.PNG" width="40%">

@hanslelee 내 물물교환 > 교환중인 항목을 탭하면 우측과 같이 에러가 뜹니다..! 
언뜻 봤을때는 서버 dto랑 모바일에 설정된 객체랑 멤버변수가 안맞춰진 것 같기도 한데..  제가 한 부분이 아니라 확실히 모르겠어서요ㅜㅜ
확인 부탁드려도 될까요?

**Comment by hanslelee** [comment]
엇 발견 감사합니다!! 제가 한달전에 지금 작업하는 브랜치에서 exchange 응답부분쪽을 수정한 것 같긴한데 너무 오래돼서 헷갈리네요ㅠㅠㅠ 다시 확인해보고 공부해보겠습니다 감사합니당👍👍👍
