### ISSUE TITLE
물품 수정하기 관련 버그

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#45]
물품 수정하기 부분이 잘 동작하지 않아서 이슈에 올려둡니당
productId 가 넘어가야 하는데 userId 가 넘어가고 있는 것 같아요!

한슬님이 작성하신 부분이라 직접 수정하시는게 나을 것 같아서요 시간되실때 확인 부탁드립니다😃
<img width="761" alt="스크린샷 2023-01-05 오후 6 05 39" src="https://user-images.githubusercontent.com/70498432/210742501-fe7ac782-ebec-4357-9cd0-abf7f7d96e53.png">
<img width="761" alt="스크린샷 2023-01-05 오후 6 05 48" src="https://user-images.githubusercontent.com/70498432/210742519-ceab4f96-4b6b-49e3-a425-cee2b01ba02a.png">

**Comment by hanslelee** [comment]
발견해주셔서 감사합니다!! 수정해서 PR 올려놓았습니다 😊
