### ISSUE TITLE
전역에서 userId 를 사용하기 위한 방법이 있을까요?

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#48]
@hanslelee 지금까지 User 값들을 임의로 만들어두고 쓰다 보니현재 대부분 UserProvider.userId 를 통해서 가져오고 있는데요 (그래서 계속 1번 유저로만 사용되네요 ㅠㅠ) 
이부분 userId가 필요한 경우마다  Provider.of<UserProvider>(context, listen: false).user.userId 이런식으로 가져와야하는걸까요? 아니면 편하게 쓸 수 있는 방법이 있을까요..?

<img width="974" alt="스크린샷 2023-01-11 오후 6 49 48" src="https://user-images.githubusercontent.com/70498432/211773710-7b23923e-e3a0-4eae-8eb6-72501053fc5a.png">
그리고 애초에  NavadaApp 클래스에서 userId를 넘겨주어야하는 클래스들이 있는 것 같아요.. 이부분도 해결이 필요할 듯 싶습니다!

관련해서 혹시 알고계신 방법이 있는지 도움 구하고 싶습니다!

**Comment by hanslelee** [comment]
@minji1110 UserProvider에서 유저 객체 자체를 static으로 변경해보았습니다! 보기 편하시게 pr 했는데 확인해보시고 알려주세용!
