### ISSUE TITLE
물품 상세보기 화면 오버플로우

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-mobile-app#53]
아이폰8 에뮬레이터 기준 물품 상세보기 화면에 오버플로우가 나는 것 같습니다!
<img width="257" alt="image" src="https://user-images.githubusercontent.com/51855129/212852960-31dd7b7b-6d1d-49cc-8895-9d67d36547bb.png">
현재는 스크롤 부분이 물품 설명에 되어있는 것 같은데, 물품설명이 아닌 전체 화면을 스크롤로 감싸는 건 어떻게 생각하세요?! 더 사용하기 시원할 것 같기도 합니다

몸도 안좋으신데 무리하지 마시고 부디 천천히 수정해주세요!!

**Comment by minji1110** [comment]
전체 스크롤 좋은 아이디어인 것 같아요!! 수정하겠습니다
교환 신청하기 버튼도 스크롤 내리면 보여지도록 할까요 아니면 스택으로 해서 버튼은 계속 아래에 떠있게 좋을까요?
몸 조금 나아지면 반영하겠습니당🥰

**Comment by hanslelee** [comment]
네네 천천히 해주세용!! 움 그러게요... 저는 둘다 좋습니다!! 민지님 해보시고 편해보이는 걸로 해주셔도 될 것 같습니다👍👍👍

**Comment by minji1110** [comment]
스택형식으로 변경해서 수정해두었습니다!
다음번 pr때 함께 올릴테니 그때 다시 한 번 확인 부탁드립니당!
