### ISSUE TITLE
몇몇 접근에서 403 Forbidden 에러가 발생합니다

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#55]
@hanslelee 몇몇 주소로 접근했을때 아래와 forbidden 에러가 뜨는데, 혹시 jwt 관련해서 따로 설정해야하는게 있을까요,,?! ㅠㅠ
 
<img width="890" alt="스크린샷 2023-01-25 오후 12 59 10" src="https://user-images.githubusercontent.com/70498432/214476975-d32fbddc-2b78-4484-a3f3-3f99582eeadb.png">

**Comment by hanslelee** [comment]
아이구 제가 바꾼다고 다 바꿨는데 아직 남은게 있군요ㅠㅠㅠ 다음과 같이 getRequest나 postRequtest등등을 호출할 때 tokenYn = true로만 설정해주시면 됩니다!!
```dart
// 교환완료
  Future<Exchange?> completeExchange(int exchangeId, bool isAcceptor) async {
    Map<String, dynamic> data = await _httpClient.patchRequest(
        '/exchange/$exchangeId?isAcceptor=$isAcceptor', {},
        tokenYn: true); //이부분이요!!

    if (data['success']) {
      return Exchange.fromJson(data['data']);
    } else {
      return null;
    }
  }
```

**Comment by minji1110** [comment]
앗 그렇군요! 참고해서 안되는부분들 수정했습니당 감사합니다!!
