### ISSUE TITLE
회원정보 : 휴대폰번호 관련 버그

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#64]
@hanslelee 회원정보 수정 기능을 테스트했는데, 수정하고 나니 아래 화면처럼 휴대폰번호 보여지는 형식이 요상하네용
이부분 확인 부탁드립니다! 백앤드에 저장도 저 형태로 되는듯합니다!
![KakaoTalk_Photo_2023-02-25-16-08-27](https://user-images.githubusercontent.com/70498432/221343992-1de4fa82-c06b-446b-a476-5e06a23ac945.jpeg)

**Comment by hanslelee** [comment]
발견 감사합니다!! 이번 스프린트 때 수정해서 pr 드리도록 하겠습니당!
