### ISSUE TITLE
탈퇴후 재가입시 userId 업데이트가 안되는 듯 합니다

### ISSUE THREAD

**Issue by minji1110** [Hi-DN/navada-mobile-app#67]
카카오톡 유저 탈퇴후(5번 유저) 재가입 했는데(6번 유저), 
앱상에서는 userId가 계속 5번으로 남아있는듯 합니다 ㅠㅠ 모든 쿼리가 다 5번으로 나가네용 .. ㅠ
이부분도 한슬님은 작동 하는지 확인 부탁드리겠습니다!

**Comment by hanslelee** [comment]
@minji1110 엇 안그래도 이부분 테스트하다가 acceptor_product_id가 null이 안돼서 회원 탈퇴가 안되는 경우가 있다고 말씀드리려는 걸 깜빡했네요 ㅜㅜ 회원탈퇴할 때 상품 삭제가 안돼서 더 테스트를 진행하지 못했는데 회의할 때 말하려다 잊혀졌네요... 죄송합니다 ㅠㅠ 
이번 백엔드 수정할 때 acceptor_product_id와 같은 컬럼들 null 허용해서 pr 해도 될까요?? 

위에 말씀하신 부분(유저 탈퇴시 앱 restart할 때 유저 정보 초기화)도 이번에 추가해서 pr 드리겠습니다 감사합니다!
